_target_: src.tuners.lgbm_tuner.LGBMTuner
hparams:
  learning_rate:
    low: 1e-4
    high: 1e-1
    log: True
  n_estimators:
    low: 8
    high: 1024
    step: 1
    log: True
  lambda_l1:
    low: 1e-8
    high: 1.0
  lambda_l2:
    low: 1e-8
    high: 1.0
  num_leaves:
    low: 2
    high: 512
    log: False
  max_depth:
    low: 1
    high: 20
    log: False
  feature_fraction:
    low: 1e-1
    high: 1.0
  bagging_fraction:
    low: 1e-1
    high: 1.0
  bagging_freq:
    low: 0
    high: 15
    log: False
  min_child_samples:
    low: 1
    high: 100
    log: False
  subsample:
    low: 1e-1
    high: 1.0
  colsample_bytree:
    low: 1e-1
    high: 1.0
  reg_alpha:
    low: 0.0
    high: 1.0
  reg_lambda:
    low: 0.0
    high: 10.0

direction: ${direction}
seed: ${seed}
num_trials: ${num_trials}
objective_name: ${objective_name}
metric_name: ${metric_name}
num_folds: ${num_folds}
hparams_save_path: ${hparams_save_path}