_target_: src.architectures.xgb_architecture.XGBArchitecture
project_name: ${project_name}
user_name: ${user_name}
save_detail: ${save_detail}
num_folds: ${num_folds}
seed: ${seed}
is_tuned: ${is_tuned}
hparams_save_path: ${hparams_save_path}
objective_name: ${objective_name}
metric_name: ${metric_name}
early_stop: ${early_stop}
model_save_path: ${model_save_path}
result_summary_path: ${result_summary_path}
plt_save_path: ${plt_save_path}
label_column_name: ${label_column_name}
submission_save_path: ${submission_save_path}