# @package _global_
defaults:
  - dataset: severity_dataset
  - architecture: cb_architecture
  - tuner: cb_tuner
  - hydra: hydra

package_name: severity-prediction
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2024

split_ratio: 2e-1
columns_mapping_file_path: metadata/columns_mapping.json
is_all_features: False
unusing_features:
  - patient_id
  - admission_date
  - discharge_date
  - transfer_date
  - discharge_to_admission_days
label_encoder_path: label_encoders
label_column_name: transfer_status
scale_type: unscale
num_folds: 5

objective_name: Logloss
metric_name: F1
early_stop: 10

model_name: CatBoost
dataset_name: severity_features
mode: train

is_tuned: tuned
direction: maximize
num_trials: 100
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_folds}/${metric_name}-${direction}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
save_detail: ${model_name}/${dataset_name}/${is_tuned}/${num_folds}

model_save_path: ${connected_dir}/save_model/${save_detail}
result_summary_path: ${connected_dir}/result_summary/${save_detail}
plt_save_path: ${connected_dir}/feature_importance/${save_detail}
submission_save_path: ${connected_dir}/submission/${save_detail}

user_name: ${oc.env:USER_NAME}
api_key: ${oc.env:API_KEY}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}