# @package _global_
defaults:
  - dataset: huggingface_burnskin_dataset
  - architecture: huggingface_architecture
  - tuner: huggingface_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: burn-vs-all
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2024

num_labels: 4

split:
  train: train
  val: val
  test: test
  predict: predict

batch_size: 32
workers_ratio: 8
use_all_workers: False

split_ratio: 0.1
classification_type: 0
is_crop: True
image_path_column_name: file_name 
target_column_name: label
coordinates_column_name:
  x1: x1
  y1: y1
  x2: x2
  y2: y2
image_size: 224
upload_user: microsoft
model_type: swin-large-patch4-window7-224-in22k
pretrained_model_name: ${upload_user}/${model_type}

lr: 1e-4
weight_decay: 1e-2
half_period: 1e-0
eta_min_ratio: 1e-2

monitor: val_MulticlassF1Score
tracking_direction: max
patience: 2
min_delta: 0

devices: ${oc.decode:${oc.env:DEVICES}}
accelerator: gpu
strategy: ddp
log_every_n_steps: 10
precision: 32
accumulate_grad_batches: 1
gradient_clip_val: 1
gradient_clip_algorithm: norm
epoch: 20

model_name: HuggingFace_${model_type}
dataset_name: BurnSkinImages
mode: train

is_tuned: untuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs=${batch_size}x${devices}x${accumulate_grad_batches}
save_detail: ${model_type}-classification_type=${classification_type}-precision=${precision}-${total_batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch=${epoch}.ckpt

submission_file_name: test
logit_name: ${save_detail}-epoch=${epoch}
submission_name: ${save_detail}-epoch=${epoch}

user_name: ${oc.env:USER_NAME}
model_detail: ${model_type}
upload_tag: burn-skin-images
num_safetensors: 1

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}