# @package _global_
defaults:
  - dataset: severity_dataset
  - architecture: xgb_architecture
  - tuner: xgb_tuner
  - hydra: hydra

package_name: severity-prediction
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2024

label_column_name: target
scale_type: unscale
num_folds: 5

objective_name: reg:squarederror
metric_name: rmse

model_name: XGBoost
dataset_name: SeverityFeatures
mode: train

is_tuned: untuned
direction: minimize
num_trials: 100
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${tuning_way}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
save_detail: ${model_name}-${dataset_name}-${num_folds}-${is_tuned}

model_save_path: ${connected_dir}/save_model/${model_name}/${dataset_name}/${is_tuned}
result_summary_path: ${connected_dir}/result_summary/${model_name}/${dataset_name}/${is_tuned}
plt_save_path: ${connected_dir}/feature_importance/${model_name}/${dataset_name}/${is_tuned}
submission_save_path: ${connected_dir}/submission

user_name: ${oc.env:USER_NAME}
run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}